Post.create(title: 'Mark',      content: 'Otto', in_stock: true)
Post.create(title: 'Jacob',     content: 'Otto', in_stock: true)
Post.create(title: 'Larry',     content: 'Otto', in_stock: false)
Post.create(title: 'Bird',      content: 'Otto', in_stock: false)
Post.create(title: 'Thornton',  content: 'Otto', in_stock: false)
Post.create(title: 'Bootstrap', content: 'Otto', in_stock: true)
Post.create(title: 'Demitriy',  content: 'Otto', in_stock: true)